name: tests

on: 
  push:
      branches:
          - master

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - name: PHP8.1
            os: ubuntu-latest
            php: '8.1'
            phpunit: '10.5'
          - name: PHP8.3
            os: ubuntu-latest
            php: '8.3'
            phpunit: '11.5'
          - name: PHP8.4
            os: ubuntu-latest
            php: '8.4'
            phpunit: '11.5'
          - name: Windows
            os: windows-latest
            php: '8.4'
            phpunit: '11.5'
          - name: macOS
            os: macos-latest
            php: '8.4'
            phpunit: '11.5'

    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer, phpstan
          ini-values: "memory_limit=512M"
          extensions: mbstring
        env:
          fail-fast: true

      - name: Checkout codes
        uses: "actions/checkout@v4"

      - name: Composer
        run: |
          composer update
          composer require --dev phpunit/phpunit=^${{ matrix.phpunit }}

      - name: PHP Static Analysys
        run: phpstan

      - name: PHPUnit Tests
        run: vendor/bin/phpunit -c tests
